
NEWS_TYPE_CHANGE_ARTWORK = 'change-artwork'
NEWS_TYPE_NEW_ARTWORK = 'new_artwork'

MAX_COMMENT_PACK = 10

MAX_ARTWORK_NAME_LENGTH = 200
MAX_ARTWORK_DESCRIPTION_LENGTH = 5000
MAX_COMMENT_LENGTH = 1000
MAX_NICKNAME_LENGTH = 100
