runtime: python27
api_version: 1
threadsafe: yes

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  
libraries:
- name: django
  version: "1.4"
  
- name: PIL
  version: "1.1.7"
  
  
handlers:
- url: /bootstrap
  static_dir: static/bootstrap
  secure: always

- url: /typeahead
  static_dir: static/typeahead
  secure: always

- url: /tagmanager
  static_dir: static/tagmanager
  secure: always
  
- url: /bootstrap-tagsinput
  static_dir: static/bootstrap-tagsinput
  secure: always

- url: /social-likes
  static_dir: static/social-likes
  secure: always
  
- url: /font-awesome
  static_dir: static/font-awesome
  secure: always  

- url: /js
  static_dir: static/js
  secure: always

- url: /css
  static_dir: static/css
  secure: always
  
- url: /img
  static_dir: static/img
  secure: always
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /ads.txt
  static_files: static/ads.txt
  upload: static/ads.txt
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
  secure: always

- url: /android-chrome-192x192.png
  static_files: static/android-chrome-192x192.png
  upload: static/android-chrome-192x192.png
  secure: always

- url: /android-chrome-256x256.png
  static_files: static/android-chrome-256x256.png
  upload: static/android-chrome-256x256.png
  secure: always

- url: /favicon-16x16.png
  static_files: static/favicon-16x16.png
  upload: static/favicon-16x16.png
  secure: always

- url: /favicon-32x32.png
  static_files: static/favicon-32x32.png
  upload: static/favicon-32x32.png
  secure: always

- url: /mstile-150x150.png
  static_files: static/mstile-150x150.png
  upload: static/mstile-150x150.png
  secure: always

- url: /browserconfig.xml
  static_files: static/browserconfig.xml
  upload: static/browserconfig.xml
  secure: always

- url: /safari-pinned-tab.svg
  static_files: static/safari-pinned-tab.svg
  upload: static/safari-pinned-tab.svg
  secure: always

- url: /site.webmanifest
  static_files: static/site.webmanifest
  upload: static/site.webmanifest
  secure: always

- url: /google5c784bef2ace5509.html
  static_files: static/google5c784bef2ace5509.html
  upload: static/google5c784bef2ace5509.html
  secure: always
  
- url: /cron/.*
  script: main.application
  login: admin  

- url: /tasks/.*
  script: main.application
  login: admin  

- url: /.*
  script: main.application
  secure: always
