application: grid-paint
version: 0-59
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  
libraries:
- name: django
  version: "1.5"
  
- name: PIL
  version: "1.1.7"

handlers:
- url: /bootstrap
  static_dir: static/bootstrap
  secure: optional

- url: /typeahead
  static_dir: static/typeahead
  secure: optional

- url: /tagmanager
  static_dir: static/tagmanager
  secure: optional
  
- url: /bootstrap-tagsinput
  static_dir: static/bootstrap-tagsinput
  secure: optional

- url: /social-likes
  static_dir: static/social-likes
  secure: optional
  
- url: /font-awesome
  static_dir: static/font-awesome
  secure: optional  

- url: /js
  static_dir: static/js
  secure: optional

- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img
  secure: optional
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional
  
- url: /google5c784bef2ace5509.html
  static_files: static/google5c784bef2ace5509.html
  upload: static/google5c784bef2ace5509.html
  secure: optional


- url: /.*
  script: main.application
  secure: optional
