application: grid-paint
version: 0-07
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.5"
  
- name: PIL
  version: "1.1.7"

handlers:
- url: /bootstrap
  static_dir: static/bootstrap

- url: /tagmanager
  static_dir: static/tagmanager

- url: /social-likes
  static_dir: static/social-likes
  
- url: /font-awesome
  static_dir: static/font-awesome  

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: main.application
