application: grid-paint
version: 0-01
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.5"

handlers:
- url: /bootstrap
  static_dir: static/bootstrap
  
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img

- url: /.*
  script: main.application
